<?xml version="1.0" encoding="utf-8"?> 
<!DOCTYPE sass [
<!ELEMENT sass (intro, compAreas)>
   <!ELEMENT intro (program, version, subversion, commentary, author, supervisorkey)>
     <!ELEMENT program (#PCDATA)>
	 <!ELEMENT version (#PCDATA)>
	 <!ELEMENT subversion (#PCDATA)>
	 <!ELEMENT commentary (#PCDATA)>
	 <!ELEMENT author (#PCDATA)>
	 <!ELEMENT supervisorkey (#PCDATA)>
   <!ELEMENT compAreas (compArea*)>
   <!ELEMENT compArea (compAreaTitle, compAreaCaption, comps)>
     <!ELEMENT compAreaTitle (#PCDATA)>
	 <!ELEMENT compAreaCaption (#PCDATA)>
	 <!ELEMENT comps (comp*)>
	   <!ELEMENT comp (compTitle, compCaption, items)>
	     <!ELEMENT compTitle (#PCDATA)>
	     <!ELEMENT compCaption (BSc, MSc)>
	       <!ELEMENT BSc (#PCDATA)>
		   <!ELEMENT MSc (#PCDATA)>
		 <!ELEMENT items (item*)>
	       <!ELEMENT item (itemTitle, itemCaption, itemLevels, itemProofs)>
	         <!ELEMENT itemLevels (itemLevel*)>
		       <!ATTLIST itemLevels caption CDATA #REQUIRED>
		     <!ELEMENT itemProofs (itemProof*)>
		       <!ATTLIST itemProofs caption CDATA #REQUIRED>
		     <!ELEMENT itemTitle (#PCDATA)>
		     <!ELEMENT itemCaption (#PCDATA)>
	         <!ELEMENT itemLevel (#PCDATA)>
	         <!ELEMENT itemProof (#PCDATA)>
]>
<sass>
	<intro>
		<program>MSc_Fusion_Science</program>
		<version>1</version>
		<subversion>0</subversion>
		<commentary>Ruimte voor commentaar</commentary>
		<author>kvo</author>
		<supervisorkey>202cb962ac59075b964b07152d234b70</supervisorkey>
	</intro>
	<compAreas>
		<compArea>
			<compAreaTitle>Disciplinary Knowledge</compAreaTitle>
			<compAreaCaption>I. This section addresses your level of disciplinary knowledge.</compAreaCaption>
			<comps>
				<comp>
					<compTitle>Knowledge Base</compTitle>
					<compCaption>
						<BSc>Understands the knowledge base of the relevant fields (theories, methods, techniques)</BSc>
						<MSc>Has a thorough mastery of parts of the relevant fields extending to the forefront of knowledge (latest theorems, methods, techniques and topical questions).</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>A1. Knowledge of the theory of MHD</itemTitle>
							<itemCaption>Knowledge of the theory of MHD refers to a body of generally accepted insights. Theoretical knowledge in general describes how the central concepts of a discipline are interrelated. It relates to the state-of-the-art knowledge within a scientific discipline.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of theoretical knowledge of MHD?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I have heard of some of the concepts of MHD, more in particular flux surfaces, conservation laws, instabilities,  and their interrelations</itemLevel>
								<itemLevel>I recall the above concepts of MHD, and how they are interrelated in terms of laws, interactions, measurements and/or interventions</itemLevel>
								<itemLevel>I can apply theoretical knowledge on MHD to conventional problems in the discipline, such as the pen-and-paper assignments in any introductory (although not non-popularized) text on MHD</itemLevel>
								<itemLevel>I can apply theoretical knowledge on MHD to problems in the discipline that are currently under active research, such as sawteeth, neoclassical tearing modes, beta limit.</itemLevel>
								<itemLevel>I can revise some concepts of the theory of MHD and / or their interrelations to fulfil a need such as advanced operating scenario?s, resisitive MHD</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of theoretical knowledge of MHD?">
								<itemProof>I have trained applying theoretical knowledge on MHD to practical problems such as pressure balance,heat transport</itemProof>
								<itemProof>I have trained applying theoretical knowledge on MHD to textbook problems of textbooks such as Freidberg</itemProof>
								<itemProof>I reflected on a particular topic from the theory on MHD in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have shown examples of the application of theoretical knowledge on MHD, other than by making textbook exercises</itemProof>
								<itemProof>I have asked probing questions to my supervisors / teachers to extend my theoretical knowledge on MHD after I had tried to solve these questions myself</itemProof>
								<itemProof>I have devised a glossary of the relevant terms from MHD theory</itemProof>
								<itemProof>I have explained concepts of MHD theory to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained concepts of MHD theory to fellow students in a plenary setting</itemProof>
								<itemProof>I have  identified the need to revise a concept from the theory of MHD  as it is presented in any textbook such as Freidberg</itemProof>
								<itemProof>I have made adjustment(s) to one or more concepts from the theory of MHD as it is presented in textbooks such as Freidberg</itemProof>
							</itemProofs>
						</item>
						<item>
							<itemTitle>A2. Knowledge of the theory of plasma diagnostics</itemTitle>
							<itemCaption>Knowledge of the theory of plasma diagnostics refers to a body of generally accepted insights. Theoretical knowledge in general describes how the central concepts of a discipline are interrelated. It relates to the state-of-the-art knowledge within a scientific discipline.</itemCaption>							<itemLevels caption="Which of the following describes best your level of theoretical knowledge of plasma diagnostics?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I have heard of some of the concepts of plasma diagnostics, more in particular ECE, interferometry, Thomson scattering,  and their interrelations</itemLevel>
								<itemLevel>I recall the above concepts of plasma diagnostics, and how they are interrelated in terms of laws, interactions, measurements and/or interventions</itemLevel>
								<itemLevel>I can apply theoretical knowledge on plasma diagnostics to conventional problems in the discipline, such as the pen-and-paper assignments in any introductory (although not non-popularized) text on plasma diagnostics</itemLevel>
								<itemLevel>I can apply theoretical knowledge on plasma diagnostics to problems in the discipline that are currently under active research, such as non-thermal ECE radiation</itemLevel>
								<itemLevel>I can revise some concepts of the theory of plasma diagnostics and / or their interrelations to fulfil a need such as sawtooth control</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of theoretical knowledge on plasma diagnostics?">
								<itemProof>I have trained applying theoretical knowledge on plasma diagnostics to practical problems such as assessments</itemProof>
								<itemProof>I have trained applying theoretical knowledge on plasma diagnostics to textbook problems of textbooks such as Hutchinson, exam</itemProof>
								<itemProof>I reflected on a particular topic from the theory on plasma diagnostics in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have shown examples of the application of theoretical knowledge on plasma diagnostics, other than by making textbook exercises</itemProof>
								<itemProof>I have asked probing questions to my supervisors / teachers to extend my theoretical knowledge on plasma diagnostics after I had tried to solve these questions myself</itemProof>
								<itemProof>I have devised a glossary of the relevant terms from plasma diagnostics theory</itemProof>
								<itemProof>I have explained concepts of plasma diagnostics theory to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained concepts of plasma diagnostics theory to fellow students in a plenary setting</itemProof>
								<itemProof>I have  identified the need to revise a concept from the theory of plasma diagnostics  as it is presented in any textbook such as Hutchinson,  lecture notes</itemProof>
								<itemProof>I have made adjustment(s) to one or more concepts from the theory of plasma diagnostics as it is presented in textbooks such as Hutchinson</itemProof>
							</itemProofs>
						</item>
						<item>
							<itemTitle>A3. Knowledge of the theory of plasmaheating</itemTitle>
							<itemCaption>Knowledge of the theory of plasma heating refers to a body of generally accepted insights. Theoretical knowledge in general describes how the central concepts of a discipline are interrelated. It relates to the state-of-the-art knowledge within a scientific discipline.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of theoretical knowledge of plasma heating?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I have heard of some of the concepts of plasma heating, more in particular neutral beam heating, ohmic heating, ECRH,  and their interrelations</itemLevel>
								<itemLevel>I recall the above concepts of plasma heating, and how they are interrelated in terms of laws, interactions, measurements and/or interventions</itemLevel>
								<itemLevel>I can apply theoretical knowledge on plasma heating to conventional problems in the discipline, such as the pen-and-paper assignments in any introductory (although not non-popularized) text on plasma heating</itemLevel>
								<itemLevel>I can apply theoretical knowledge on plasma heating to problems in the discipline that are currently under active research, such as current drive, advanced scenarios</itemLevel>
								<itemLevel>I can revise some concepts of the theory of plasma heating and / or their interrelations to fulfil a need such as current drive, advanced scenarios</itemLevel>
							</itemLevels>
							<itemProofs caption="How did I achieve this level of theoretical knowledge on plasmaheating?">
								<itemProof>I have trained applying theoretical knowledge on plasma heating to practical problems such as assignments, exams</itemProof>
								<itemProof>I have trained applying theoretical knowledge on plasma heating to textbook problems of textbooks such as Freidberg, Wesson</itemProof>
								<itemProof>I reflected on a particular topic from the theory on plasma heating in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have shown examples of the application of theoretical knowledge on plasma heating, other than by making textbook exercises</itemProof>
								<itemProof>I have asked probing questions to my supervisors / teachers to extend my theoretical knowledge on plasma heating after I had tried to solve these questions myself</itemProof>
								<itemProof>I have devised a glossary of the relevant terms from plasma heating theory</itemProof>
								<itemProof>I have explained concepts of plasma heating theory to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained concepts of plasma heating theory to fellow students in a plenary setting</itemProof>
								<itemProof>I have  identified the need to revise a concept from the theory of plasma heating  as it is presented in any textbook such as Freidberg, Wesson</itemProof>
								<itemProof>I have made adjustment(s) to one or more concepts from the theory of plasma heating as it is presented in textbooks such as Freidberg, Wesson</itemProof>
							</itemProofs>
						</item>
						<item>
							<itemTitle>A4. Knowledge of the theory of single particle motions</itemTitle>
							<itemCaption>Knowledge of the theory of single particle motions refers to a body of generally accepted insights. Theoretical knowledge in general describes how the central concepts of a discipline are interrelated. It relates to the state-of-the-art knowledge within a scientific discipline.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of theoretical knowledge of single particle motions?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I have heard of some of the concepts of single particle motions, more in particular drifts, adiabatic constants, trapping,  and their interrelations</itemLevel>
								<itemLevel>I recall the above concepts of single particle motions, and how they are interrelated in terms of laws, interactions, measurements and/or interventions</itemLevel>
								<itemLevel>I can apply theoretical knowledge on single particle motions to conventional problems in the discipline, such as the pen-and-paper assignments in any introductory (although not non-popularized) text on single particle motions</itemLevel>
								<itemLevel>I can apply theoretical knowledge on single particle motions to problems in the discipline that are currently under active research, such as bootstrap current, trapped particles</itemLevel>
								<itemLevel>I can revise some concepts of the theory of single particle motions and / or their interrelations to fulfil a need such as for runaway electrons</itemLevel>
							</itemLevels>
							<itemProofs caption="How did I achieve this level of theoretical knowledge of single particle motions?">
								<itemProof>I have trained applying theoretical knowledge on single particle motions to practical problems such as test exams, assignment</itemProof>
								<itemProof>I have trained applying theoretical knowledge on single particle motions to textbook problems of textbooks such as Freidberg, Chen, Wesson</itemProof>
								<itemProof>I reflected on a particular topic from the theory on single particle motions in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have shown examples of the application of theoretical knowledge on single particle motions, other than by making textbook exercises</itemProof>
								<itemProof>I have asked probing questions to my supervisors / teachers to extend my theoretical knowledge on single particle motions after I had tried to solve these questions myself</itemProof>
								<itemProof>I have devised a glossary of the relevant terms from single particle motions theory</itemProof>
								<itemProof>I have explained concepts of single particle motions theory to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained concepts of single particle motions theory to fellow students in a plenary setting</itemProof>
								<itemProof>I have  identified the need to revise a concept from the theory of single particle motions  as it is presented in any textbook such as Freidberg, Chen, Wesson</itemProof>
								<itemProof>I have made adjustment(s) to one or more concepts from the theory of single particle motions as it is presented in textbooks such as Freidberg, Chen, Wesson</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Structure</compTitle>
					<compCaption>
						<BSc>Understands the structure of the relevant fields, and the connections between sub-fields.</BSc>
						<MSc>Looks actively for structure and connections in the relevant fields.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>B. Knowledge of the structure of a discipline</itemTitle>
							<itemCaption>Scientific fields are generally made up of a multitude of sub-disciplines. For example, both thermodynamicsand quantum mechanics are considered to be part of physics. Both sub-disciplines are significantly different,but share some characteristics which make them both part of physics. Structural knowledge covers anunderstanding of the internal organization of a scientific discipline.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of knowledge of the structure of a discipline?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I realize that the discipline(s) I am studying  has / have  a structure</itemLevel>
								<itemLevel>I can mention some features of the structure of the discipline(s) I am studying, that is: pairs of key concepts and the relation that connects them</itemLevel>
								<itemLevel>I am able to map out the structure of the discipline(s) I am studying, that is: I am able to draw a graph containing key concepts as points, and meaningfully label the connecting arcs where this graph contains at least some 50 key concepts and 150 arcs</itemLevel>
								<itemLevel>I am able to point out similarities in structure between subfields of the discipline(s) I am studying, that is: I can give examples of parts from the graph from the previous question where I can explain the structural differences and similarities between these parts</itemLevel>
							</itemLevels>
							<itemProofs caption="How did I achieve this  level of knowledge of the structure of a discipline?">
								<itemProof>I took lectures in several sub-disciplines</itemProof>
								<itemProof>I identified the structure of the discipline(s) I am studying, making lists of key concepts and their connections</itemProof>
								<itemProof>I made a schematic diagram (for instance in the form of  a graph) of the discipline(s) I am studying, showing the structure</itemProof>
								<itemProof>I searched for similarities and differences between various sub-disciplines in a graph, representing the structure of the discipline</itemProof>
								<itemProof>I have explained the structure of the discipline to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained the structure of the discipline to fellow students in a pleanry setting</itemProof>
								<itemProof>I have made assignments that require an understanding of  the structure of the discipline</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Truth-finding</compTitle>
					<compCaption>
						<BSc>Has knowledge of and some skill in the way in which truth-finding and the development of theories and models take place in the relevant fields</BSc>
						<MSc>Has the skill and the attitude to apply these methods independently in the context of more advanced ideas or applications</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>C. Knowledge of discipline-specific methods</itemTitle>
							<itemCaption>Scientific disciplines differ in the way new ideas and hypotheses are tested before they are adopted into the body of generally accepted insights. For example, formal consistency is the primary test for new mathematical arguments, whereas in empirical disciplines new ideas are often probed with experiments. Knowledge of discipline-specific methods covers how theoretical development takes place in a given scientific discipline.</itemCaption>
							<itemLevels caption="Which of the following describes your  level of knowledge of discipline-specific methods?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I realize that developing a scientific discipline involves methods</itemLevel>
								<itemLevel>I can mention the most important standard methods of the discipline(s) I am studying</itemLevel>
								<itemLevel>When I work on a problem in my discipline, I can mention which method I am using at any moment</itemLevel>
								<itemLevel>I am able to effectively apply the standard methods to standard problems</itemLevel>
								<itemLevel>I am able to effectively apply the standard methods to novel problems</itemLevel>
								<itemLevel>I am able to adapt the methods of the discipline</itemLevel>
								<itemLevel>I am able to devise a new method in my discipline</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of knowledge?">
								<itemProof>I have read about discipline-specific methods</itemProof>
								<itemProof>I have trained the usage of discipline-specific methods in dedicated textbook assignments</itemProof>
								<itemProof>I have applied some discipline-specific methods to non-textbook assignments</itemProof>
								<itemProof>I have reflected on discipline-specific methods in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have explained methods in the discipline to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained methods in the discipline to fellow students in a pleanry setting</itemProof>
								<itemProof>I have compiled summaries on discipline-specific methods</itemProof>
								<itemProof>I have read / studied examples of methodologically flawed scientific projects</itemProof>
								<itemProof>I have compiled a glossary of relevant terms regarding methodology</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Interpretation</compTitle>
					<compCaption>
						<BSc>Has knowledge of and some skill in the way in which interpretations (texts, data, problems, results) take place in the relevant fields.</BSc>
						<MSc>Has the skill and the attitude to apply these methods independently in the context of more advanced ideas or applications.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>F. Knowledge about proper inference from data</itemTitle>
							<itemCaption>Data can take many formats and are normally subjected to some analysis. Dependent on the type of analysis, these results have to be interpreted.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of knowledge about proper inference from data?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I am able to mention an example of inference from data</itemLevel>
								<itemLevel>I am able to explain the consequences of making proper inferences</itemLevel>
								<itemLevel>I am able to recall the elements of proper inferences that apply in my discipline (for instance, fitting parameters, making qualitative distinctions, ?)</itemLevel>
								<itemLevel>I am able to use the elements of proper inferences in idealised situations (say, in lab assignments)</itemLevel>
								<itemLevel>I am able to make proper inferences on the correct level of accuracy (reliability, certainty, ?)</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of knowledge about proper inference from data?">
								<itemProof>I have done practical assignments involving inference from data</itemProof>
								<itemProof>I have done textbook assignments that hinge on the inference from data</itemProof>
								<itemProof>I have reflected on the principles of proper inferences, starting from a question I posed myself</itemProof>
								<itemProof>I have compiled notes on inference from data</itemProof>
								<itemProof>I have explained inference to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained inference to fellow students in a plenary setting</itemProof>
								<itemProof>I have asked questions to my supervisors on inference, after having tried to answer these questions myself</itemProof>
								<itemProof>I have used methods for inference in the course of a practical project</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Experiments</compTitle>
					<compCaption>
						<BSc>Has knowledge of and some skill in the way in which experiments, gathering of data and simulations take place in the relevant fields.</BSc>
						<MSc>Has the skill and the attitude to apply these methods independently in the context of more advanced ideas or applications.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>E. Knowledge about experimenting, data gathering and/or simulation</itemTitle>
							<itemCaption>Empirical research depends on data. Data can be obtained by empirical experimentation  (producing new data), collecting existing data, or simulation (that is, generating data by executing a model system instead of a real system)  In mechanical engineering, for instance, the strength of various materials is measured.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of knowledge about data gathering?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I know the meaning, role and function of experimenting, data gathering and simulation</itemLevel>
								<itemLevel>I recall methods for experimenting, data gathering and/or simulation</itemLevel>
								<itemLevel>I am able to effectively obtain data according to textbook methods for experimenting, data gathering and/or simulation in an idealized setting</itemLevel>
								<itemLevel>I am able to effectively obtain data in realistic settings using experiments, data gathering and/or simulation</itemLevel>
								<itemLevel>I am able to develop a novel method for obtaining data by experiment, data gathering and/or simulation</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of knowledge?">
								<itemProof>I have done assignments on the methods for obtaining data</itemProof>
								<itemProof>I have used a standard method for obtaining data in a practical project</itemProof>
								<itemProof>I have compiled notes about obtaining data</itemProof>
								<itemProof>I have explained methods for obtaining data to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained methods for obtaining data to fellow students in a plenary setting</itemProof>
								<itemProof>I have taken in a course on either experimental techniques or simulation</itemProof>
								<itemProof>I have studied examples of scientific explorations that failed because of inappropriate methods for obtaining data</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Decision-making</compTitle>
					<compCaption>
						<BSc>Has knowledge of and some skill in the way in which decision-making takes place in the relevant fields.</BSc>
						<MSc>Has the skill and the attitude to apply these methods independently in the context of more advanced ideas or applications.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>no item</itemTitle>
							<itemCaption>no item caption</itemCaption>
							<itemLevels caption="-- no text --">
								<itemLevel> -- nothing -- </itemLevel>
							</itemLevels>
							<itemProofs caption="-- no text --">
								<itemProof> -- nothing -- </itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Presuppositions</compTitle>
					<compCaption>
						<BSc>Is aware of both the presuppositions of the standard methods and their importance.</BSc>
						<MSc>Is able to refl ect on standard methods and their presuppositions; is able to question these; is able to propose adjustments, and to estimate their implications.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>D. Knowledge of presuppositions</itemTitle>
							<itemCaption>Application of standard methods in any scientific discipline is based on presuppositions. For instance, probability theory can be used to calculate the odds of winning with a certain hand of cards in a game of black jack only if the assumption of a uniform distribution is met, i.e. the deck of cards is properly shuffled before the game.</itemCaption>
							<itemLevels caption="Which of the following describes best your level of knowledge regarding presuppositions?">
								<itemLevel>I possess no such level of knowledge</itemLevel>
								<itemLevel>I realize that procedures and models assume presuppositions to hold</itemLevel>
								<itemLevel>I am able to mention some examples of presuppositions that need to hold for some of the standard methods in my discipline</itemLevel>
								<itemLevel>I know the critical presuppositions behind procedures and models in my discipline for most common procedures and models</itemLevel>
								<itemLevel>I am able to check whether presuppositions are valid in my scientific work</itemLevel>
								<itemLevel>I routinely check whether presuppositions are valid in my scientific work</itemLevel>
								<itemLevel>I have the attitude not to apply any method unless I verified all critical presuppositions</itemLevel>
								<itemLevel>I am able to come up with alternative presuppositions when circumstances require this</itemLevel>
							</itemLevels>
							<itemProofs caption="How did you achieve this level of knowledge?">
								<itemProof>I have investigated the presuppositions behind procedures and models</itemProof>
								<itemProof>I have taken a course in the methodology of science</itemProof>
								<itemProof>I have reflected on presuppositions in a structured manner, starting from a question I posed myself</itemProof>
								<itemProof>I have compiled notes about the presuppositions behind procedures and models</itemProof>
								<itemProof>I have explained presuppositions to fellow students in a 1-to-1 setting</itemProof>
								<itemProof>I have explained presuppositions to fellow students in a plenary setting</itemProof>
								<itemProof>I have collected examples of scientific explorations that have failed because of flawed presuppositions</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Revise and Extend</compTitle>
					<compCaption>
						<BSc>Is able (with supervision) to spot gaps in his / her own knowledge, and to revise and extend it through study</BSc>
						<MSc>Idem, independently.</MSc>
					</compCaption>
					<items>
						<item>
							<itemTitle>no item</itemTitle>
							<itemCaption>no item caption</itemCaption>
							<itemLevels caption="-- no text --">