<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE sass [
<!ELEMENT sass (intro , compAreas)>
<!ELEMENT intro (program , version , subversion , commentary , author , supervisorkey)>
<!ELEMENT program (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT subversion (#PCDATA)>
<!ELEMENT commentary (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT supervisorkey (#PCDATA)>
<!ELEMENT compAreas (compArea)*>
<!ELEMENT compArea (compAreaTitle , compAreaCaption , comps)>
<!ELEMENT compAreaTitle (#PCDATA)>
<!ELEMENT compAreaCaption (#PCDATA)>
<!ELEMENT comps (comp)*>
<!ELEMENT comp (compTitle , compCaption , items)>
<!ELEMENT compTitle (#PCDATA)>
<!ELEMENT compCaption (BSc , MSc)>
<!ELEMENT BSc (#PCDATA)>
<!ELEMENT MSc (#PCDATA)>
<!ELEMENT items (item)*>
<!ELEMENT item (itemTitle , itemCaption , itemLevels , itemProofs)>
<!ELEMENT itemProofs (itemProof)*>
<!ATTLIST itemProofs caption CDATA #REQUIRED>
<!ELEMENT itemTitle (#PCDATA)>
<!ELEMENT itemCaption (#PCDATA)>
<!ELEMENT itemProof (#PCDATA)>
<!ATTLIST itemProof ProofID CDATA #REQUIRED>
]>
<sass>
	<intro>
		<program>MSc_Fusion_Science</program>
		<version>1</version>
		<subversion>0</subversion>
		<commentary>Ruimte voor commentaar</commentary>
		<author>kvo</author>
		<supervisorkey>202cb962ac59075b964b07152d234b70</supervisorkey>
	</intro>
	<compAreas>
		<compArea>
			<compAreaTitle>Doing Research</compAreaTitle>
			<compAreaCaption>"This competency area explores your skills in executing research. Research is the development and probing of new knowledge and new insights in a purposeful and systematic manner. 
When answering the questions below, please note that there are no correct or incorrect answers; it is about your own assessment of your skills and expertise. If you cannot answer a question, for example because a certain skill is not applicable to you, or because you do not know the answer, then pick the “do not know / not applicable” response option. You can reflect on the possibilities to develop this skill in the near future, or perhaps talk to your supervisor for assistance."
</compAreaCaption>
			<comps>
				
				<comp>
					<compTitle>Ability to reformulate research questions</compTitle>
					<items>
						<item>
							<itemTitle>Ability to reformulate research questions</itemTitle>
							<itemCaption>The question at the beginning of a research project is often ill-defined and cannot be researched properly. It first has to be reformulated in terms of relevant scientific theories, measurement procedures, etc. Then it should be applied to an appropriate format for testable hypotheses. After reformulation, the new interpretation has to be defended against involved parties. 
							</itemCaption>
							<itemProofs caption="-- no text --">
								<itemProof ProofID="0">I usually know when a research question in my discipline is properly phrased </itemProof>
								<itemProof ProofID="1">I have successfully used concept maps, or some other means of structuring relationships between relevant concepts, for the reformulation of ill-defined questions</itemProof>
								<itemProof ProofID="2">I have performed a reformulation of a design problem</itemProof>
								<itemProof ProofID="3">I have identified a case of conflicting requirements</itemProof>
								<itemProof ProofID="4">I sometimes have difficulties defining p roper procedures, to test a hypothesis</itemProof>
								<itemProof ProofID="5">I sometimes find it difficult to understand why certain ill-defined research questions are deemed non-testable</itemProof>
								<itemProof ProofID="6">I usually find it easy to correctly identify a research question as being non-testable</itemProof>
								<itemProof ProofID="7">I am competent in defending my (re)formulated research question against involved parties</itemProof>
								<itemProof ProofID="8">I can usually tell beforehand whether a selected procedure will answer a particular research question</itemProof>
							</itemProofs>
						</item>
					</items>
				</comp>
				
				<comp>
					<compTitle>Creativity</compTitle>
					<items>
						<item>
							<itemTitle>Creativity</itemTitle>
							<itemCaption>In science, a researcher has to be able to discover new and unconventional connections and adopt alternative points of view. These connections may or may not lead to variations of existing viewpoints or approaches. It involves being observant, and having the creativity and capacity to discover in apparently trivial matters certain connections and new viewpoints in order to come up with solutions. After discovering the new connections, the next ability is to put these viewpoints into practice for new applications.
</itemCaption>
							<itemProofs caption="-- no text --">
							
								<itemProof ProofID="0">I usually have no difficulties in discovering a new and unconventional connection</itemProof>
								<itemProof ProofID="1">I know that a new and unconventional connection sometimes leads to a variation of an existing viewpoint or approach</itemProof>
								<itemProof ProofID="2">I sometimes fail to see that a particular approach is a variation of an existing one </itemProof>
								<itemProof ProofID="3">I have heard of m ethods / techniques to seek for variations to well known procedures or viewpoints </itemProof>
								<itemProof ProofID="4">I sometimes have difficulties finding methods to seek variations to well known procedures or viewpoints </itemProof>
								<itemProof ProofID="5">I always try to stick to my own approach until I solved a problem</itemProof>
								<itemProof ProofID="6">I sometimes have difficulties encouraging my creative thinking </itemProof>
								<itemProof ProofID="7">I have successfully applied techniques to find alternative solutions in everyday life situations </itemProof>
								<itemProof ProofID="8">I have successfully applied techniques to find alternative solutions in technological settings </itemProof>
								<itemProof ProofID="9">I sometimes find it hard to (apply techniques to) find alternative solutions</itemProof>
								<itemProof ProofID="10">I have successfully inspired fellow students to find unconventional solutions to research problems</itemProof>
								<itemProof ProofID="11">I am usually proficient in applying techniques to find alternative solutions in the course of my project work</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>

				<comp>
					<compTitle>Ability to implement research plans</compTitle>
					<items>
						<item>
							<itemTitle>Ability to implement research plans</itemTitle>
							<itemCaption>Research involves multiple tasks (e.g. data collection, experimental set-up, measurements, analysis of the data). Often these tasks are only mapped out in general terms beforehand, leaving the details of the implementation to the individual researcher. It involves the ability to execute a given research plan, decide in what order and in addition how to carry out the tasks. The ability to produce and execute a research plan is important as being a researcher. 
</itemCaption>
							<itemProofs caption="-- no text --">
								<itemProof>I usually know how to implement a given research plan that describes what tasks, in what order and how to carry out the tasks</itemProof>
<itemProof>I sometimes tend to lose track with regard to the phase of the project that I am in</itemProof>
<itemProof>Given a project plan, merely described as an ordered list of tasks, I can usually decide how to carry out these tasks</itemProof>
<itemProof>Given a project plan, merely described as an unordered collection of tasks, I sometimes have difficulties how to schedule these tasks</itemProof>
<itemProof>In general, I have no difficulties in  breaking down a task in several sub tasks</itemProof>
<itemProof>Doing the tasks in the right order is usually easy for me</itemProof>
<itemProof>During the implementation of a research plan, I constantly monitor whether the original plan needs to be updated (e.g., by changing the order of tasks) </itemProof>
<itemProof>I sometimes find it hard to notice when the order of tasks need to be revised</itemProof>
<itemProof>I usually have no difficulties implementing my own research plan based on the research question, without any guidance </itemProof>
<itemProof>I often underestimate the time it takes to carry out the tasks that need to be done</itemProof>
<itemProof>I am usually able to correctly analyze the external resources needed to execute a task</itemProof>
<itemProof>I am proficient in managing a research project </itemProof>
<itemProof>I have successfully helped fellow students to set up their research plan</itemProof>
<itemProof>I am usually confident in devising different plans and evaluate which is the best</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				
				<comp>
					<compTitle>Ability to think at various levels of abstraction</compTitle>
					<items>
						<item>
							<itemTitle>Ability to think at various levels of abstraction</itemTitle>
							<itemCaption>In research, the phenomenon under investigation is often described on different levels of abstraction. These levels can be distinguished by the type of statements that are made to describe the phenomenon (e.g. the goal of a phenomenon is abstract, its means to achieve the goals are concrete).  As a researcher it is important to be able to work at different levels of abstraction. Depending on the maturity of the research problem, one chooses the appropriate level of abstraction. 
</itemCaption>
							<itemProofs caption="-- no text --">
								<itemProof>I am usually confident in explaining the characteristics of a phenomenon in informal terms </itemProof>
<itemProof>I am usually confident in explaining the characteristics of a phenomenon in informal terms </itemProof>
<itemProof>It would be easy for me  to formalize the specifics of the phenomenon mathematically  </itemProof>
<itemProof>Manipulating the abstract formalization of the phenomenon to obtain quantitative outcomes is easy for me</itemProof>
<itemProof>I sometimes have difficulties with using  an abstract formalization (e.g., a theory) of the phenomenon to obtain quantitative outcomes about real-life instantiations of the phenomenon</itemProof>
<itemProof>I sometimes find it difficult to describe discrepancies between  the phenomenon and its abstract representation</itemProof>
<itemProof>I used mathematics to obtain quantitative outcomes of the phenomenon </itemProof>
<itemProof>using mathematics to verify a known feature of the phenomenon is easy for me </itemProof>
<itemProof>using mathematics to verify a known feature of the phenomenon is easy for me </itemProof>
<itemProof>I have discussed the use of mathematics in my discipline with fellow students</itemProof>
<itemProof>I explained the use of mathematics to fellow students </itemProof>
<itemProof>I have encountered situations in which I succeeded in using the same mathematical representation to describe  multiple phenomena</itemProof>
<itemProof>I am proficient in discussing the weaknesses of an inadequate application of theoretical / conceptual abstraction</itemProof>
 <itemProof>I am proficient in discussing the strengths and weaknesses of a given application of a mathematical abstraction</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				
				<comp>
					<compTitle>Interdisciplinarity: Ability to integrate knowledge from several disciplines</compTitle>
					<items>
						<item>
							<itemTitle>Interdisciplinarity: Ability to integrate knowledge from several disciplines</itemTitle>
							<itemCaption>In modern science, interdisciplinary research becomes more and more prevalent. Interdisciplinary research often requires merging knowledge, methods and concepts from distinct scientific disciplines. It is important to know about the relevance of other disciplines, and where necessary to use knowledge from other disciplines in own research. 
</itemCaption>
							<itemProofs caption="-- no text --">
								<itemProof>I sometimes have difficulties in explaining my research problem to scholars from other disciplines</itemProof>
<itemProof>I know examples of theories or methods from disciplines other than my own</itemProof>
<itemProof>I frequently expand my knowledge about other disciplines (by for example reading a book, taking a course from other disciplines, or doing exercises to explore connections between disciplines)</itemProof>
<itemProof>I sometimes have difficulties with using theories or methods from other disciplines in my own research</itemProof>
<itemProof>I am proficient in working on research problems requiring the merge of knowledge, methods, and concepts from distinct disciplines </itemProof>
<itemProof>I am proficient in working on research problems requiring the merge of knowledge, methods, and concepts from distinct disciplines </itemProof>
<itemProof>I am proficient in working on research problems requiring the merge of knowledge, methods, and concepts from distinct disciplines </itemProof>
<itemProof>I sometimes reflect on my own research from the perspective of another discipline</itemProof>
<itemProof>I sometimes reflect on my own research from the perspective of another discipline</itemProof>
<itemProof>I am usually confident to talk with students from a different domain regarding research topics general to their discipline</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				
				<comp>
					<compTitle>Ability to appraise scientific evidence</compTitle>
					<items>
						<item>
							<itemTitle>Ability to appraise scientific evidence</itemTitle>
							<itemCaption>In applied research, scientific knowledge from literature is used to solve practical problems. To make use of published literature, a researcher must first be able to search for relevant knowledge, then assess the soundness of the reported evidence accordingly. Next, the quality of the (empirical) argument and methods used in terms of their scientific value should be assessed. 
</itemCaption>
							<itemProofs caption="-- no text --">
								<itemProof>I know that existing knowledge is available to aid in understanding and solving a research problem</itemProof>
<itemProof>I know how to search for relevant knowledge in the published literature that helps me solving a research problem</itemProof>
<itemProof>When searching for published research results, I usually find it easy to identify the correct search terms and / or criteria</itemProof> 
<itemProof>I know which sources of published research results (e.g., which journals) are relevant for my domain </itemProof>
<itemProof>I am proficient in estimating the relevance of a particular research result for a problem at hand </itemProof>
<itemProof>I sometimes have difficulties with estimating the soundness of a reported piece of evidence </itemProof>
<itemProof>I systematically read original research publications in my domain</itemProof>
<itemProof>I sometimes recommend published research results to others </itemProof>
<itemProof>I sometimes have difficulties assessing the quality of scientific literature in a critical way</itemProof>
<itemProof>Comparing and analysing two contradictory papers on the some research topic is usually easy for me</itemProof>
<itemProof>It is sometimes hard for me to spot weaknesses in published scientific arguments </itemProof>
<itemProof>I have identified a published scientific result as insufficient for my purpose </itemProof>
<itemProof>I am confident that I can mention the quality criteria for the reproducibility of published scientific results</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				
				
			</comps>
		</compArea>
		<compArea>
			<compAreaTitle>Design</compAreaTitle>
			<compAreaCaption>This competency area explores your ability to design products/systems. With design, we mean the development of new or modified products/systems or parts thereof, with the intention of creating gains in accordance with predefined value (e.g. functionality, efficiency, usability).</compAreaCaption>
			<comps>
				<comp>
					<compTitle>Ability to reformulate design problems</compTitle>
					<items>
						<item>
							<itemTitle>Ability to reformulate design problems</itemTitle>
							<itemCaption>The design objective as formulated by the other parties (e.g. supervisors, stakeholders etc.), often need reconsideration before it can be technically addressed. A designer should be able to reformulate the design problem, and argue for his or her reformulation. 
</itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>It is usually easy for me to identifying the interests of the various parties involved in the design project (i.e. ,the stakeholders)</itemProof>
<itemProof>I sometimes find it difficult to explore systematically the wishes of other parties  involved in the design project</itemProof>
<itemProof>I can successfully apply methods to extract technical requirements from the wishes of the various parties involved in the design project (i.e. ,the stakeholders)</itemProof>
<itemProof>I sometimes find it difficult to identify possible cases of conflicting requirements; i.e., cases where two or more requirements may not be implemented together</itemProof>
<itemProof>I usually find it easy to resolve a case of conflicting requirements</itemProof>
<itemProof>I usually find it easy to reformulate the design problem into an applicable set of technical requirements</itemProof>
<itemProof>I am proficient in defending the reformulation of the design problem against involved parties</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Creativity</compTitle>
					<items>
						<item>
							<itemTitle>Creativity</itemTitle>
							<itemCaption>A designer has to be able to find new and unconventional connections and adopt alternative points of view. These connections may or may not lead to variations of existing viewpoints or approaches. It involves being observant, and having the creativity and capacity (e.g. by using techniques to generate ideas and concepts) to discover certain connections and new viewpoints in order to come up with design solutions on problems. These solutions range from well known to extremely unorthodox. Creativity relates to the ability to propose unconventional solutions. 
</itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>I usually have no difficulties in discovering a new and unconventional connection</itemProof>
<itemProof>I know that a new and unconventional connection sometimes leads to a variation of an existing viewpoint or approach</itemProof>
<itemProof>I usually find it easy to identify when some design solution is a variation of some other design solution</itemProof>
<itemProof>I have heard of m ethods to search for variations to well known design solutions</itemProof>
<itemProof>I know of multiple methods to search for variations to well known design solutions</itemProof>
<itemProof>I sometimes find it difficult to search for variations to well known design solutions</itemProof>
<itemProof>I routinely use one or more methods to search for variations to well known design solutions</itemProof>
<itemProof>I am proficient in discovering different design solutions</itemProof>
<itemProof>I usually find it easy to inspire fellow students to find unconventional solutions to design problems </itemProof>
<itemProof>I sometimes have difficulties applying techniques to find alternative solutions in the course of my project work</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Ability to implement design plans</compTitle>
					<items>
						<item>
							<itemTitle>Ability to implement design plans</itemTitle>
							<itemCaption>Designing involves multiple tasks (e.g. sketching, prototyping, testing). Often these tasks are only mapped out in general terms beforehand, leaving the details of the implementation to the individual designer. The easiest step for a designer, is to execute a plan that describes all steps, their order and how to carry out the steps. It gets more difficult when the plan does not describe how to carry out the steps, or even the order of the steps. Implementing a design plan involves planning skills. 
</itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>I usually have no difficulties with implementing a given design plan that describes what tasks, in what order and how to carry out the tasks</itemProof>
<itemProof>I sometimes tend to lose track with regard to the phase of the project that I am in</itemProof>
<itemProof>Given a project plan, merely described as an ordered list of tasks, I am usually able to carry out these tasks</itemProof>
<itemProof>Given a project plan, merely described as an unordered collection of tasks, I sometimes have difficulties in determining how to carry out these tasks</itemProof>
<itemProof>In general, I have no difficulties in  breaking down a task in several sub tasks</itemProof>
<itemProof>Doing the tasks in the right order is usually easy for me</itemProof>
<itemProof>During the implementation of a design plan, I constantly monitor whether the original plan needs to be updated (e.g., by changing the order of tasks) </itemProof>
<itemProof>I sometimes find it hard to notice when the order of tasks need to be revised</itemProof>
<itemProof>I usually have no difficulties implementing my own design plan based on the design requirements, without any guidance </itemProof>
<itemProof>I often underestimate the time it takes to carry out the tasks that need to be done </itemProof>
<itemProof>I am usually able to correctly analyze the external resources needed to execute a task</itemProof>
<itemProof>I am proficient in managing a design project </itemProof>
<itemProof>I have successfully helped fellow students to set up their design plan</itemProof>
<itemProof>I am usually confident in devising different plans and evaluate which is the best</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Ability to work at various levels of integration (abstraction)</compTitle>
					<items>
						<item>
							<itemTitle>Ability to work at various levels of integration (abstraction) </itemTitle>
							<itemCaption>Products or systems in technological design usually have a complex structure, function, and behaviour. These products/systems can be understood at different levels of integration: at a concrete level involving elements, or at a more abstract level involving processes. The ability to work at various levels of integration refers to the capability to take advantage of the different views on the product/system offered by the levels in the design process. 
</itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>I usually find it easy to distinguish between concrete (elements) and abstract (processes) levels</itemProof>
<itemProof>I sometimes have difficulties identifying elements in a process level design </itemProof>
<itemProof>I usually find it easy to decompose a process level design into the required elements</itemProof>
<itemProof>I usually have no difficulties with analyzing existing products/systems at different levels of integration</itemProof>
<itemProof>I am proficient in designing individual elements and integrating them. in a process level design</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				<comp>
					<compTitle>Integrate existing knowledge </compTitle>
					<items>
						<item>
							<itemTitle>Integrate existing knowledge </itemTitle>
							<itemCaption>With modern technology, interdisciplinary design is common place. Professionals from various disciplines work together and knowledge from different domains has to be integrated. In other words, interdisciplinary design requires merging knowledge, methods and concepts from various disciplines. 
</itemCaption>
							<itemProofs caption="-- no text --">
<itemProof>I know that existing knowledge is available to inspire and aid in working on a design case </itemProof>
<itemProof>I know how to find information from the right design related databases</itemProof>
<itemProof>I systematically make use of original publications on research to argument on my design directions</itemProof>
<itemProof>When searching for original publications or inspiring designs, I usually have no difficulties in identifying the relevant search terms</itemProof>
<itemProof>Comparing and analysing two different designs with the same goal, is usually easy for me</itemProof>
<itemProof>I have identified existing designs as insufficient for my purpose</itemProof>
<itemProof>I sometimes find it difficult to select the most relevant information to implement in my design case</itemProof>
<itemProof>I am proficient in integrating the information in a design solution or prototype</itemProof>


							</itemProofs>
						</item>
					</items>
				</comp>
				
				<comp>
					<compTitle>Ability to integrate knowledge from several disciplines (Interdiciplinarity)</compTitle>
					<items>
						<item>
							<itemTitle>Ability to integrate knowledge from several disciplines (Interdiciplinarity)</itemTitle>
							<itemCaption></itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>I usually find it easy to explain my design project to scholars from other disciplines</itemProof>
<itemProof>I sometimes find it difficult to identify theories and methods from other disciplines that are relevant to solving my design project</itemProof>
<itemProof>I sometimes have difficulties with using theories and methods from other disciplines in my own design project</itemProof>
<itemProof>I am proficient in working on design problems requiring the merge of knowledge (methods and concepts) from different disciplines</itemProof>
<itemProof>I sometimes have difficulties with identifying parallels and differences between different disciplines with regard to how design problems are solved</itemProof>
<itemProof>I am proficient in identifying differences in the design process (its purpose and methodology) between different disciplines </itemProof>
<itemProof>I sometimes reflect on my own designs from the perspective of another discipline</itemProof>
<itemProof>I am usually confident to have integrated theories and methods from other disciplines in a correct manner into my design project</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
				
				
				<comp>
					<compTitle>Take well-justified design decisions</compTitle>
					<items>
						<item>
							<itemTitle>Take well-justified design decisions</itemTitle>
							<itemCaption></itemCaption>
							<itemProofs caption="-- no text --">
				<itemProof>I am usually confident that I can identify all the decisions that were made during a design project (conscious and subconscious decisions)</itemProof>
<itemProof>Keeping track of my design decisions is sometimes difficult for me</itemProof>
<itemProof>Usually it is easy for me to see when a design decision is well-justified </itemProof>
<itemProof>I sometimes find it difficult to give a justification of a design decision in hindsight</itemProof>
<itemProof>Defending my decisions against critical comments is sometimes difficult for me</itemProof>
<itemProof>I usually have no difficulties basing my design decisions on a priori considerations</itemProof>
<itemProof>I am confident in helping fellow students to justify their design decisions</itemProof>
<itemProof>It is easy for me to point out decisions based on wrong argumentation in the design of others </itemProof>
<itemProof>I have re-considered design decisions on the basis of critical analysis</itemProof>

							</itemProofs>
						</item>
					</items>
				</comp>
			</comps>
		</compArea>
		
	</compAreas>
</sass>
